makepng:
	inkscape actions.svg --export-png actions.png --export-dpi 22.5
	inkscape status-online.svg --export-png status-online.png --export-dpi 17
	inkscape status-offline.svg --export-png status-offline.png --export-dpi 17
	inkscape status-disabled.svg --export-png status-disabled.png --export-dpi 17

clean:
	rm -f actions.png
	rm -f status-online.png
	rm -f status-offline.png
	rm -f status-disabled.png
